### ISSUE TITLE
Why Liquid Haskell Matters syntax errors

### ISSUE THREAD

**Issue by andrewthad** [tweag/blog-resources#16]
In "Why Liquid Haskell Matters" (which is fantastically written by the way), there is an example of a refined data type:

```
{-@
data UExp
  = UVar {i:Int | 0 <= i} // indices are specified to be non-negative
  | ULam UExp
  | UApp UExp UExp
@-}
data UExp
  = UVar Int
  | ULam UExp
  | UApp UExp UExp
```

However, liquid haskell needs the value in the `UVar` data constructor to be wrapped in parentheses to parse it correctly:

```
data UExp
  = UVar ({i:Int | 0 <= i})
  | ...
```

At least, the latest liquid haskell does. This example may have worked fine when the blog post was originally written.

**Comment by facundominguez** [comment]
Thanks @andrewthad! I submitted a fix.Now, those parenthesis are so ugly :stuck_out_tongue: ...

I'm glad to learn that you enjoyed the post!

**Comment by guaraqe** [comment]
This was fixed in the post now. Thanks!
