### ISSUE TITLE
`nix-shell` fails in `monad-bayes-series`

### ISSUE THREAD

**Issue by curiousleo** [tweag/blog-resources#4]
```console
$ nix-shell
[...]
> /nix/store/98fqirs1dkvm240kn72jj1s2ifd5xx3y-nodejs-10.16.3/bin/npm pack jupyterlab-ihaskell
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! network request to https://registry.npmjs.org/jupyterlab-ihaskell failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2019-11-04T13_21_51_057Z-debug.log

Errored, use --debug for full output:
ValueError: "jupyterlab-ihaskell" is not a valid npm package
builder for '/nix/store/y6adzmayqwy62h129jbndf8gvr6546r8-jupyterlab-extended.drv' failed with exit code 1
building '/nix/store/141dpbcn222c9j6vfkzk4x2kw3922z9n-SHA-1.6.4.4.drv'...
cannot build derivation '/nix/store/r5nhlzghk0jh0nds6rmj3h97bm07yqss-python3.7-jupyterlab-0.35.6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/r5nhlzghk0jh0nds6rmj3h97bm07yqss-python3.7-jupyterlab-0.35.6.drv', '/nix/store/wvrkhr418k31gmhd16kf26094q800gaz-ihaskell-kernel.drv' failed
```

Note that this is probably an issue with `jupyterWith` or some other upstream library and not with `monad-bayes-series`. But I'm not sure what the root issue actually is, so I'm creating this issue here.

Unfortunately I don't know where `/build/.npm/_logs/2019-11-04T13_21_51_057Z-debug.log` can be found.

The only relevant information about this failure that I could find is this: https://logs.nix.samueldr.com/nixos/2019-02-24#1988813;
>  22:32 <earldouglas> Something about DNS not working during mkDerivation.

**Comment by curiousleo** [comment]
@MMesch tell me that the `nix-shell` sandbox needs to be turned off. I get:

```console
$ nix-shell --option sandbox false
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
```

I haven't investigated exactly what I need to do to make `--option sandbox false` work, but it seems kind of ugly anyway.

I think it would be good to make it such that that `--option sandbox false` was not necessary.

**Comment by guaraqe** [comment]
We show how to solve that in JupyterWith's repository, we should put a link to the README here, as long as we don't solve the npm problem.

**Comment by curiousleo** [comment]
`nix-shell` is still running and hasn't failed yet, so changing `nix.trustedUsers` plus `--option sandbox false` seems to work. Next up: https://github.com/tweag/jupyterWith/issues/49
